package de.adfcommunity.altaui.model.queries;

import de.adfcommunity.altaui.model.queries.common.ProductWarehouseShiftView;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 30 11:55:03 CET 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductWarehouseShiftViewImpl extends ViewObjectImpl implements ProductWarehouseShiftView {
    /**
     * This is the default constructor (do not remove).
     */
    public ProductWarehouseShiftViewImpl() {
    }
    
    public void changeStockToValue(Integer warehouseId,Integer amountInStock){
        
        Row activeRow = this.first();
        
        int i = 0;
        while(i< this.getEstimatedRowCount()){
            
            Integer activeWarehouseId = (Integer)activeRow.getAttribute("WarehouseId");
            
            if(activeWarehouseId.equals(warehouseId)){
                activeRow.setAttribute("AmountInStock", amountInStock);
                break;
            }
            
            activeRow = this.next();
        }
        
    }
}

