package de.adfcommunity.altaui.model.queries.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 30 12:47:31 CET 2015
// ---------------------------------------------------------------------
public interface ProductWarehouseShiftView extends ViewObject {
    void changeStockToValue(Integer warehouseId, Integer amountInStock);
}

