package oracle.summit.model.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 14 15:00:30 BST 2011
// ---------------------------------------------------------------------
public interface CustomerVO extends ViewObject {
    void unsetCustomerViewCriteria();
}
