package oracle.summit.model.views.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 12 17:53:38 BST 2011
// ---------------------------------------------------------------------
public interface ItemVORow extends Row {
    void deleteOrderItem();
}
