package oracle.summit.model.views;

import java.util.List;

import oracle.jbo.ViewCriteria;

import oracle.summit.base.SummitViewObjectImpl;
import oracle.summit.model.views.common.CustomerVO;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 14 14:59:21 BST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustomerVOImpl extends SummitViewObjectImpl implements CustomerVO {
    /**
     * This is the default constructor (do not remove).
     */
    public CustomerVOImpl() {
    }

    /**
     * Sample exportable method.
     */
    public void sampleCustomerVOImplExportable() {
    }

    /**
     * Sample exportable method.
     */
    public void sampleCustomerVOImplExportable2(String testParam1) {
    }

    /**
     * Sample exportable method.
     */
    public List<String> sampleCustomerVOImplExportable3(List<String> listParam,
                                                        String testParam1) {
        return listParam;
    }
    
  public void unsetCustomerViewCriteria (){
      ViewCriteria vc = getViewCriteria("CustomerViewCriteria");
      vc.resetCriteria();
      applyViewCriteria(vc);
      executeQuery();
      }
}
