package oracle.summit.model.views.client;

import oracle.jbo.client.remote.ViewUsageImpl;

import oracle.summit.model.views.common.CustomerVO;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 14 15:00:30 BST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustomerVOClient extends ViewUsageImpl implements CustomerVO {
    /**
     * This is the default constructor (do not remove).
     */
    public CustomerVOClient() {
    }

    public void unsetCustomerViewCriteria() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"unsetCustomerViewCriteria",null,null);
        return;
    }
}
