package oracle.summit.model.views.client;

import oracle.jbo.client.remote.RowImpl;

import oracle.summit.model.views.common.ItemVORow;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 12 17:53:39 BST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ItemVORowClient extends RowImpl implements ItemVORow {
    /**
     * This is the default constructor (do not remove).
     */
    public ItemVORowClient() {
    }

    public void deleteOrderItem() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"deleteOrderItem",null,null);
        return;
    }
}
