package oracle.summit.model.entities;

import java.sql.Date;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;

import oracle.summit.base.SummitEntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 23 15:17:15 GMT 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OrdEOImpl extends SummitEntityImpl {

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Id {
            public Object get(OrdEOImpl obj) {
                return obj.getId();
            }

            public void put(OrdEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CustomerId {
            public Object get(OrdEOImpl obj) {
                return obj.getCustomerId();
            }

            public void put(OrdEOImpl obj, Object value) {
                obj.setCustomerId((Number) value);
            }
        }
        ,
        DateOrdered {
            public Object get(OrdEOImpl obj) {
                return obj.getDateOrdered();
            }

            public void put(OrdEOImpl obj, Object value) {
                obj.setDateOrdered((Date) value);
            }
        }
        ,
        DateShipped {
            public Object get(OrdEOImpl obj) {
                return obj.getDateShipped();
            }

            public void put(OrdEOImpl obj, Object value) {
                obj.setDateShipped((Date) value);
            }
        }
        ,
        SalesRepId {
            public Object get(OrdEOImpl obj) {
                return obj.getSalesRepId();
            }

            public void put(OrdEOImpl obj, Object value) {
                obj.setSalesRepId((Number) value);
            }
        }
        ,
        Total {
            public Object get(OrdEOImpl obj) {
                return obj.getTotal();
            }

            public void put(OrdEOImpl obj, Object value) {
                obj.setTotal((Number) value);
            }
        }
        ,
        PaymentTypeId {
            public Object get(OrdEOImpl obj) {
                return obj.getPaymentTypeId();
            }

            public void put(OrdEOImpl obj, Object value) {
                obj.setPaymentTypeId((Integer) value);
            }
        }
        ,
        OrderFilled {
            public Object get(OrdEOImpl obj) {
                return obj.getOrderFilled();
            }

            public void put(OrdEOImpl obj, Object value) {
                obj.setOrderFilled((String) value);
            }
        }
        ,
        ItemEO {
            public Object get(OrdEOImpl obj) {
                return obj.getItemEO();
            }

            public void put(OrdEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CustomerEO {
            public Object get(OrdEOImpl obj) {
                return obj.getCustomerEO();
            }

            public void put(OrdEOImpl obj, Object value) {
                obj.setCustomerEO((CustomerEOImpl) value);
            }
        }
        ,
        EmpEO {
            public Object get(OrdEOImpl obj) {
                return obj.getEmpEO();
            }

            public void put(OrdEOImpl obj, Object value) {
                obj.setEmpEO((SummitEntityImpl) value);
            }
        }
        ,
        PaymentTypeEO {
            public Object get(OrdEOImpl obj) {
                return obj.getPaymentTypeEO();
            }

            public void put(OrdEOImpl obj, Object value) {
                obj.setPaymentTypeEO((SummitEntityImpl) value);
            }
        }
        ,
        PaymentOptionsVA {
            public Object get(OrdEOImpl obj) {
                return obj.getPaymentOptionsVA();
            }

            public void put(OrdEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        static AttributesEnum[] vals = null;
        ;
        private static int firstIndex = 0;

        public abstract Object get(OrdEOImpl object);

        public abstract void put(OrdEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int CUSTOMERID = AttributesEnum.CustomerId.index();
    public static final int DATEORDERED = AttributesEnum.DateOrdered.index();
    public static final int DATESHIPPED = AttributesEnum.DateShipped.index();
    public static final int SALESREPID = AttributesEnum.SalesRepId.index();
    public static final int TOTAL = AttributesEnum.Total.index();
    public static final int PAYMENTTYPEID = AttributesEnum.PaymentTypeId.index();
    public static final int ORDERFILLED = AttributesEnum.OrderFilled.index();
    public static final int ITEMEO = AttributesEnum.ItemEO.index();
    public static final int CUSTOMEREO = AttributesEnum.CustomerEO.index();
    public static final int EMPEO = AttributesEnum.EmpEO.index();
    public static final int PAYMENTTYPEEO = AttributesEnum.PaymentTypeEO.index();
    public static final int PAYMENTOPTIONSVA = AttributesEnum.PaymentOptionsVA.index();

    /**
     * This is the default constructor (do not remove).
     */
    public OrdEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("oracle.summit.model.entities.OrdEO");
    }


    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the Id
     */
    public DBSequence getId() {
        return (DBSequence) getAttributeInternal(ID);
    }


    /**
     * Gets the attribute value for CustomerId, using the alias name CustomerId.
     * @return the CustomerId
     */
    public Number getCustomerId() {
        return (Number)getAttributeInternal(CUSTOMERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerId.
     * @param value value to set the CustomerId
     */
    public void setCustomerId(Number value) {
        setAttributeInternal(CUSTOMERID, value);
    }

    /**
     * Gets the attribute value for DateOrdered, using the alias name DateOrdered.
     * @return the DateOrdered
     */
    public Date getDateOrdered() {
        return (Date)getAttributeInternal(DATEORDERED);
    }

    /**
     * Sets <code>value</code> as the attribute value for DateOrdered.
     * @param value value to set the DateOrdered
     */
    public void setDateOrdered(Date value) {
        setAttributeInternal(DATEORDERED, value);
    }

    /**
     * Gets the attribute value for DateShipped, using the alias name DateShipped.
     * @return the DateShipped
     */
    public Date getDateShipped() {
        return (Date)getAttributeInternal(DATESHIPPED);
    }

    /**
     * Sets <code>value</code> as the attribute value for DateShipped.
     * @param value value to set the DateShipped
     */
    public void setDateShipped(Date value) {
        setAttributeInternal(DATESHIPPED, value);
    }

    /**
     * Gets the attribute value for SalesRepId, using the alias name SalesRepId.
     * @return the SalesRepId
     */
    public Number getSalesRepId() {
        return (Number)getAttributeInternal(SALESREPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesRepId.
     * @param value value to set the SalesRepId
     */
    public void setSalesRepId(Number value) {
        setAttributeInternal(SALESREPID, value);
    }

    /**
     * Gets the attribute value for Total, using the alias name Total.
     * @return the Total
     */
    public Number getTotal() {
        return (Number)getAttributeInternal(TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Total.
     * @param value value to set the Total
     */
    public void setTotal(Number value) {
        setAttributeInternal(TOTAL, value);
    }


    /**
     * Gets the attribute value for OrderFilled, using the alias name OrderFilled.
     * @return the OrderFilled
     */
    public String getOrderFilled() {
        return (String)getAttributeInternal(ORDERFILLED);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderFilled.
     * @param value value to set the OrderFilled
     */
    public void setOrderFilled(String value) {
        setAttributeInternal(ORDERFILLED, value);
    }


    /**
     * Gets the attribute value for PaymentTypeId, using the alias name PaymentTypeId.
     * @return the PaymentTypeId
     */
    public Integer getPaymentTypeId() {
        return (Integer)getAttributeInternal(PAYMENTTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PaymentTypeId.
     * @param value value to set the PaymentTypeId
     */
    public void setPaymentTypeId(Integer value) {
        setAttributeInternal(PAYMENTTYPEID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getItemEO() {
        return (RowIterator)getAttributeInternal(ITEMEO);
    }

    /**
     * @return the associated entity oracle.summit.base.SummitEntityImpl.
     */
    public CustomerEOImpl getCustomerEO() {
        return (CustomerEOImpl)getAttributeInternal(CUSTOMEREO);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.summit.base.SummitEntityImpl.
     */
    public void setCustomerEO(CustomerEOImpl value) {
        setAttributeInternal(CUSTOMEREO, value);
    }

    /**
     * @return the associated entity oracle.summit.base.SummitEntityImpl.
     */
    public SummitEntityImpl getEmpEO() {
        return (SummitEntityImpl)getAttributeInternal(EMPEO);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.summit.base.SummitEntityImpl.
     */
    public void setEmpEO(SummitEntityImpl value) {
        setAttributeInternal(EMPEO, value);
    }

    /**
     * @return the associated entity oracle.summit.base.SummitEntityImpl.
     */
    public SummitEntityImpl getPaymentTypeEO() {
        return (SummitEntityImpl)getAttributeInternal(PAYMENTTYPEEO);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.summit.base.SummitEntityImpl.
     */
    public void setPaymentTypeEO(SummitEntityImpl value) {
        setAttributeInternal(PAYMENTTYPEEO, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PaymentOptionsVA.
     */
    public RowSet getPaymentOptionsVA() {
        return (RowSet) getAttributeInternal(PAYMENTOPTIONSVA);
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(DBSequence id) {
        return new Key(new Object[] { id });
    }


}
